services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: "jellyfin"
    env_file: .env
    user: 1000:1000
    group_add: # by id as these may not exist within the container. Needed to provide permissions to the VAAPI Devices
      - "107" #render
      - "44" #video
    # Network mode of 'host' exposes the ports on the host. This is needed for DLNA access.
    #        network_mode: 'host'
    networks:
      - traefik
    ports:
      - "8096:8096"
      - "7359:7359/udp"
      - "1900:1900/udp"
    volumes:
      - /srv/data/jellyfin/config:/config
      - /srv/data/jellyfin/cache:/cache
      # Update this configuration as desired
      - /mnt/media/media:/media
    restart: always
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.jellyfin.entryPoints=https"
      - "traefik.http.routers.jellyfin.rule=Host(`${HOST_DOMAIN}`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certResolver=letsencrypt"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  traefik:
    external: true
