services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    env_file: .env
    volumes:
      - /srv/data/hasshole:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      traefik.enable: true

      traefik.http.routers.homeassistant.entrypoints: https
      traefik.http.routers.homeassistant.rule: Host(`${HOST_DOMAIN}`)
      traefik.http.routers.homeassistant.tls: true
      traefik.http.routers.homeassistant.tls.certResolver: letsencrypt
      traefik.http.services.homeassistant.loadbalancer.server.port: 8123
