global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO

providers:
  docker:
    network: traefik
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    defaultRule: Host(`{{ coalesce (index .Labels "com.docker.compose.service") (normalize .Name) }}.{{ env "DOMAIN" }}`)

  file:
    directory: "./rules.d"
    watch: true

api:
  dashboard: true

ping:
  entryPoint: "ping"

entryPoints:
  ping:
    address: ":8082"
  ssh:
    address: ":22"
  grpc:
    address: ":4317"
  otlp:
    address: ":4318"
    http:
      tls:
        certResolver: letsencrypt
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1"
        - "172.50.0.0/24"
  https:
    address: ":443"
    http3: {}
    http:
      tls:
        certResolver: letsencrypt
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1"
        - "172.50.0.0/24"
    transport:
      respondingTimeouts:
        readTimeout: 300

certificatesResolvers:
  letsencrypt:
    acme:
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      storage: /acme_data/acme.json
      #httpChallenge:
      #entryPoint: http
      dnsChallenge:
        provider: "cloudflare"
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

  tailscale:
    tailscale: {}

tls:
  stores:
    default: {}
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256

experimental:
  plugins:
    traefik-real-ip:
      modulename: github.com/jramsgz/traefik-real-ip
      version: v1.0.6
